revert changes from github actions workflows

diff --git a/.github/workflows/omgx-integration.yml b/.github/workflows/omgx-integration.yml
--- a/.github/workflows/omgx-integration.yml
+++ b/.github/workflows/omgx-integration.yml
@@ -1,4 +1,4 @@
-name: integration
+name: omgx_integration
 
 on:
   push:
@@ -25,6 +25,7 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+          # aws-region: us-east-1
       - name: Start EC2 runner
         id: start-ec2-runner
         uses: machulav/ec2-github-runner@v2
@@ -36,12 +37,23 @@ jobs:
           subnet-id: subnet-905870ae
           security-group-id: sg-0855631d714870b32
 
-  integration:
+  omgx_integration:
     needs: start-runner
     runs-on: ${{ needs.start-runner.outputs.label }}
     env:
-        DOCKER_BUILDKIT: 1
-        COMPOSE_DOCKER_CLI_BUILD: 1
+      DOCKER_BUILDKIT: 1
+      COMPOSE_DOCKER_CLI_BUILD: 1
+      TEST_PRIVATE_KEY_1: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
+      TEST_PRIVATE_KEY_2: "0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba"
+      TEST_PRIVATE_KEY_3: "0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e"
+      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
+      L1_NODE_WEB3_URL: http://localhost:9545
+      L2_NODE_WEB3_URL: http://localhost:8545
+      URL: http://127.0.0.1:8080/addresses.json
+      OMGX_URL: http://127.0.0.1:8078/addresses.json
+      TARGET_GAS_LIMIT: 9000000000
+      CHAIN_ID: 28
+
     steps:
       # Monorepo tests
       - uses: actions/checkout@v2
@@ -58,23 +70,66 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-yarn-
 
+      - name: Install yq
+        run: sudo snap install yq
+
+      - name: Check the .envs
+        run: printenv
+
       - name: Build the services
         working-directory: ./ops
-        run: ./scripts/build-ci.sh
+        run: ./scripts/build-ci-omgx.sh
 
       - name: Bring the stack up
         working-directory: ./ops
-        run: |
-          ./scripts/stats.sh &
-          docker-compose -f docker-compose-base.yml up -d
+        run: docker-compose -f docker-compose.yml up -d
 
       - name: Wait for the Sequencer node
         working-directory: ./ops
         run: ./scripts/wait-for-sequencer.sh
 
-      - name: Run the integration tests
+      # - name: Build the services, bring the stack up + OMGX services
+      #   working-directory: ./ops
+      #   env:
+      #     BUILD: 1
+      #     DAEMON: 1
+      #   run: ./up_local.sh
+
+      # just sets up background logs for the system that was just started
+      # this just adds the logging
+      - name: Start background logging
         working-directory: ./ops
-        run: docker-compose run integration_tests
+        run: docker-compose -f docker-compose.yml logs --follow &
+
+      # this test jitters - in any case, later tests will fail if the OMGX_deployer does not come up
+      - name: Test serving OMGX contracts
+        working-directory: ./
+        run: |
+          RETRIES=60
+          URL=http://127.0.0.1:8078/addresses.json
+          until $(curl --silent --fail --output /dev/null "$URL"); do
+            sleep 20s
+            echo "Will wait $((RETRIES--)) more times for $URL to be up..."
+
+            if [ "$RETRIES" -lt 0 ]; then
+              echo "Timeout waiting for contract deployment"
+              exit 1
+            fi
+          done
+          echo "OMGX contracts are deployed"
+          L2LIQUIDITY_POOL=$(curl --silent $URL | jq -r .L2LiquidityPool)
+          echo $L2LIQUIDITY_POOL
+          if [[ $L2LIQUIDITY_POOL =~ "0x" ]]; then
+            exit 0
+          else
+            exit 1
+          fi
+
+      # Very time and memory consuming
+      # and simply duplicates
+      # - name: Run the base system integration tests
+      #   working-directory: ./ops
+      #   run: docker-compose run integration_tests
 
       - name: Test the base OMGX contracts
         working-directory: ./packages/omgx/contracts
@@ -86,79 +141,11 @@ jobs:
         run: |
           yarn test:integration
 
-      # Examples Tests
-      # - name: Test & deploy hardhat-example on Ethereum (regression)
-      #  working-directory: ./examples/hardhat
-      #  run: |
-      #    yarn
-      #    yarn deploy
-      #    yarn test:integration
-
-      # - name: Test & deploy hardhat-example on Optimistic Ethereum
-      #  working-directory: ./examples/hardhat
-      #  run: |
-      #    yarn deploy:ovm
-      #    yarn test:integration:ovm
-
-      #- name: Test & deploy waffle-example on Ethereum (regression)
-      #  working-directory: ./examples/waffle
-      #  run: |
-      #    yarn
-      #    yarn compile
-      #    yarn test:integration
-
-      #- name: Test & deploy waffle-example on Optimistic Ethereum
-      #  working-directory: ./examples/waffle
-      #  run: |
-      #    yarn compile:ovm
-      #    yarn test:integration:ovm
-
-      #- name: Test & deploy truffle-example on Ethereum (regression)
-      #  working-directory: ./examples/truffle
-      #  run: |
-      #    yarn
-      #    yarn compile
-      #    yarn test:integration
-      #    yarn deploy
-
-      #- name: Test & deploy truffle-example on Optimistic Ethereum
-      #  working-directory: ./examples/truffle
-      #  run: |
-      #    yarn compile:ovm
-      #    yarn test:integration:ovm
-      #    yarn deploy:ovm
-
-      # - name: Test l1-l2-deposit-withdrawal example on Optimistic Ethereum with cross-domain message passing
-      #   working-directory: ./examples/l1-l2-deposit-withdrawal
-      #   run: |
-      #     yarn
-      #     yarn compile
-      #     yarn compile:ovm
-      #     yarn test:integration:ovm
-
-      # - name: Collect docker logs on failure
-      #   if: failure()
-      #   uses: jwalton/gh-docker-logs@v1
-      #   with:
-      #     images: 'ethereumoptimism/builder,ethereumoptimism/hardhat,ethereumoptimism/deployer,ethereumoptimism/data-transport-layer,ethereumoptimism/l2geth,ethereumoptimism/message-relayer,ethereumoptimism/batch-submitter,ethereumoptimism/l2geth,ethereumoptimism/integration-tests'
-      #     dest: '~/logs'
-
-      # - name: Tar logs
-      #   if: failure()
-      #   run: tar cvzf ./logs.tgz ~/logs
-
-      # - name: Upload logs to GitHub
-      #   if: failure()
-      #   uses: actions/upload-artifact@master
-      #   with:
-      #     name: logs.tgz
-      #     path: ./logs.tgz
-
   stop-runner:
     name: Stop self-hosted EC2 runner
     needs:
       - start-runner # required to get output from the start-runner job
-      - integration # required to wait when the main job is done
+      - omgx_integration # required to wait when the main job is done
     runs-on: ubuntu-latest
     if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
     steps:
@@ -168,6 +155,7 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+          # aws-region: us-east-1
       - name: Stop EC2 runner
         uses: machulav/ec2-github-runner@v2
         with:
